class TurkeyProvince {
  final String name;
  final String key;

  const TurkeyProvince({required this.name, required this.key});
}

const List<TurkeyProvince> turkeyProvinces = [
  TurkeyProvince(name: 'Adana', key: 'adana'),
  TurkeyProvince(name: 'Adıyaman', key: 'adiyaman'),
  TurkeyProvince(name: 'Afyonkarahisar', key: 'afyonkarahisar'),
  TurkeyProvince(name: 'Ağrı', key: 'agri'),
  TurkeyProvince(name: 'Aksaray', key: 'aksaray'),
  TurkeyProvince(name: 'Amasya', key: 'amasya'),
  TurkeyProvince(name: 'Ankara', key: 'ankara'),
  TurkeyProvince(name: 'Antalya', key: 'antalya'),
  TurkeyProvince(name: 'Ardahan', key: 'ardahan'),
  TurkeyProvince(name: 'Artvin', key: 'artvin'),
  TurkeyProvince(name: 'Aydın', key: 'aydin'),
  TurkeyProvince(name: 'Balıkesir', key: 'balikesir'),
  TurkeyProvince(name: 'Bartın', key: 'bartin'),
  TurkeyProvince(name: 'Batman', key: 'batman'),
  TurkeyProvince(name: 'Bayburt', key: 'bayburt'),
  TurkeyProvince(name: 'Bilecik', key: 'bilecik'),
  TurkeyProvince(name: 'Bingöl', key: 'bingol'),
  TurkeyProvince(name: 'Bitlis', key: 'bitlis'),
  TurkeyProvince(name: 'Bolu', key: 'bolu'),
  TurkeyProvince(name: 'Burdur', key: 'burdur'),
  TurkeyProvince(name: 'Bursa', key: 'bursa'),
  TurkeyProvince(name: 'Çanakkale', key: 'canakkale'),
  TurkeyProvince(name: 'Çankırı', key: 'cankiri'),
  TurkeyProvince(name: 'Çorum', key: 'corum'),
  TurkeyProvince(name: 'Denizli', key: 'denizli'),
  TurkeyProvince(name: 'Diyarbakır', key: 'diyarbakir'),
  TurkeyProvince(name: 'Düzce', key: 'duzce'),
  TurkeyProvince(name: 'Edirne', key: 'edirne'),
  TurkeyProvince(name: 'Elazığ', key: 'elazig'),
  TurkeyProvince(name: 'Erzincan', key: 'erzincan'),
  TurkeyProvince(name: 'Erzurum', key: 'erzurum'),
  TurkeyProvince(name: 'Eskişehir', key: 'eskisehir'),
  TurkeyProvince(name: 'Gaziantep', key: 'gaziantep'),
  TurkeyProvince(name: 'Giresun', key: 'giresun'),
  TurkeyProvince(name: 'Gümüşhane', key: 'gumushane'),
  TurkeyProvince(name: 'Hakkari', key: 'hakkari'),
  TurkeyProvince(name: 'Hatay', key: 'hatay'),
  TurkeyProvince(name: 'Iğdır', key: 'igdir'),
  TurkeyProvince(name: 'Isparta', key: 'isparta'),
  TurkeyProvince(name: 'İstanbul', key: 'istanbul'),
  TurkeyProvince(name: 'İzmir', key: 'izmir'),
  TurkeyProvince(name: 'Kahramanmaraş', key: 'kahramanmaras'),
  TurkeyProvince(name: 'Karabük', key: 'karabuk'),
  TurkeyProvince(name: 'Karaman', key: 'karaman'),
  TurkeyProvince(name: 'Kars', key: 'kars'),
  TurkeyProvince(name: 'Kastamonu', key: 'kastamonu'),
  TurkeyProvince(name: 'Kayseri', key: 'kayseri'),
  TurkeyProvince(name: 'Kırıkkale', key: 'kirikkale'),
  TurkeyProvince(name: 'Kırklareli', key: 'kirklareli'),
  TurkeyProvince(name: 'Kırşehir', key: 'kirsehir'),
  TurkeyProvince(name: 'Kilis', key: 'kilis'),
  TurkeyProvince(name: 'Kocaeli', key: 'kocaeli'),
  TurkeyProvince(name: 'Konya', key: 'konya'),
  TurkeyProvince(name: 'Kütahya', key: 'kutahya'),
  TurkeyProvince(name: 'Malatya', key: 'malatya'),
  TurkeyProvince(name: 'Manisa', key: 'manisa'),
  TurkeyProvince(name: 'Mardin', key: 'mardin'),
  TurkeyProvince(name: 'Mersin', key: 'mersin'),
  TurkeyProvince(name: 'Muğla', key: 'mugla'),
  TurkeyProvince(name: 'Muş', key: 'mus'),
  TurkeyProvince(name: 'Nevşehir', key: 'nevsehir'),
  TurkeyProvince(name: 'Niğde', key: 'nigde'),
  TurkeyProvince(name: 'Ordu', key: 'ordu'),
  TurkeyProvince(name: 'Osmaniye', key: 'osmaniye'),
  TurkeyProvince(name: 'Rize', key: 'rize'),
  TurkeyProvince(name: 'Sakarya', key: 'sakarya'),
  TurkeyProvince(name: 'Samsun', key: 'samsun'),
  TurkeyProvince(name: 'Siirt', key: 'siirt'),
  TurkeyProvince(name: 'Sinop', key: 'sinop'),
  TurkeyProvince(name: 'Sivas', key: 'sivas'),
  TurkeyProvince(name: 'Şanlıurfa', key: 'sanliurfa'),
  TurkeyProvince(name: 'Şırnak', key: 'sirnak'),
  TurkeyProvince(name: 'Tekirdağ', key: 'tekirdag'),
  TurkeyProvince(name: 'Tokat', key: 'tokat'),
  TurkeyProvince(name: 'Trabzon', key: 'trabzon'),
  TurkeyProvince(name: 'Tunceli', key: 'tunceli'),
  TurkeyProvince(name: 'Uşak', key: 'usak'),
  TurkeyProvince(name: 'Van', key: 'van'),
  TurkeyProvince(name: 'Yalova', key: 'yalova'),
  TurkeyProvince(name: 'Yozgat', key: 'yozgat'),
  TurkeyProvince(name: 'Zonguldak', key: 'zonguldak'),
];
